#!/bin/bash
# Add the Ubuntu backports archive

set -eu
set -o xtrace

if [ "$DISTRO_NAME" == "ubuntu" ] && [ "$DIB_RELEASE" == "trusty" ]; then
    echo deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse > /etc/apt/sources.list.d/backports.list
elif [ "$DISTRO_NAME" == "centos7" ]; then
    echo 'exclude=shim*,mokutil*' >> /etc/yum.conf
    echo 'cancelled shim mokutil from upgrades'
    echo none!
fi
